### ISSUE TITLE
Translate: JSX In Depth

### ISSUE THREAD

**Issue by jvelezpo** [reactjs/es.reactjs.org#116]
relates to: https://github.com/reactjs/es.reactjs.org/issues/4

**Comment by carburo** [comment]
Please, do not open new issues for claiming translations. #4 is the right place to do that.

**Comment by jvelezpo** [comment]
Hello @carburo i am not claiming with an issue, i open this issue because the section was already assigned to me, look at this, and if you consider to reopen the issue it will be good,

https://github.com/reactjs/es.reactjs.org/issues/4#issuecomment-460871891

![image](https://user-images.githubusercontent.com/1050904/52410362-1f534780-2aa6-11e9-81e5-7afc3b9675ad.png)

![image](https://user-images.githubusercontent.com/1050904/52410369-22e6ce80-2aa6-11e9-9636-71e47a7ed3b6.png)

![image](https://user-images.githubusercontent.com/1050904/52410420-46117e00-2aa6-11e9-8736-aa58d53b1390.png)


Please look that i open the issue after it was assigned to me.

**Comment by carburo** [comment]
Read the first comment in #4. You dont't need to open an issue. Just send a PR.
