### ISSUE TITLE
Translate: Components and Props

### ISSUE THREAD

**Issue by EzequielMonforte** [reactjs/es.reactjs.org#14]
Translate components and props

**Comment by ElRodrigote** [comment]
Hi!

I would like to contribute taking this issue. How should I proceed? This would be my first contribution to public repos, please be patient haha.

**Comment by dmoralesm** [comment]
> Hi!
> 
> I would like to contribute taking this issue. How should I proceed? This would be my first contribution to public repos, please be patient haha.

I think this is owned by @EzequielMonforte, please see https://github.com/reactjs/es.reactjs.org/issues/4 to check what you can help with :)

**Comment by ElRodrigote** [comment]
OIC, thank you very much, will take a look =)
