### ISSUE TITLE
Translate: Conditional Rendering.

### ISSUE THREAD

**Issue by alejandronanez** [reactjs/es.reactjs.org#17]

**Comment by ElRodrigote** [comment]
I'm kinda confused as this is my first contribution to open source. Could you please give me a hand about how to proceed? I've already cloned the repo, created a branch, started translating, but tried to push my branch to create a PR and it seems I don't have access rights, is that right?

**Comment by dmoralesm** [comment]
> I'm kinda confused as this is my first contribution to open source. Could you please give me a hand about how to proceed? I've already cloned the repo, created a branch, started translating, but tried to push my branch to create a PR and it seems I don't have access rights, is that right?

Create a fork instead, then clone your fork and work there. You should be able to push your fork and then come back here and create a pull request.

**Comment by alejandronanez** [comment]
We're closing this issue to reduce the noise in the repo. The place to claim an issue is #4

Thanks! 👍
