### ISSUE TITLE
Translating the Comunity Section

### ISSUE THREAD

**Issue by carburo** [reactjs/es.reactjs.org#200]
As a first step, we could do straight translations. Additionally, as @tesseralis has pointed out it would be cool if we could also add resources in Spanish. I also opened a [conversation](https://spectrum.chat/react-espanol/traducciones/recursos-disponibles-en-espanol-sobre-react~46a61dff-76ec-4c96-add7-3e2b85434041) on Spectrum for discussing which of those resources would be a good fit.

### Community Resources

* [x] Support @RamirezAlex #207 
* [x] Courses @jpvg10 #211 
* [x] Examples @jvelezpo #216 
* [x] Meetups @RamirezAlex  #210 
* [ ] Conferences
* [x] [Articles](https://github.com/reactjs/es.reactjs.org/blob/master/content/community/articles.md) @jpmti2016
* [x] Podcasts @RamirezAlex #209 
* [x] [Videos](https://github.com/reactjs/es.reactjs.org/blob/master/content/community/videos.md) @jpmti2016
* [x] [External Resources](https://github.com/reactjs/es.reactjs.org/blob/master/content/community/external-resources.md) @gonzarodriguezt #243 
### ~~Tools~~

* [ ] ~~Debugging @mact200590  #219~~
* [ ] ~~[Component Workbenches](https://github.com/reactjs/es.reactjs.org/blob/master/content/community/tools-comp-workbenches.md) @jmmendivil~~
* [ ] ~~[JSX Integrations](https://github.com/reactjs/es.reactjs.org/blob/master/content/community/tools-jsx.md)~~
* [ ] ~~[Starter Kits](https://github.com/reactjs/es.reactjs.org/blob/master/content/community/tools-starter-kits.md)~~
* [x] ~~Routing @hextiandro #214~~
* [ ] ~~[Model Management](https://github.com/reactjs/es.reactjs.org/blob/master/content/community/tools-model-mgmt.md)~~
* [x] ~~Data Fetching @OmaritoAtPoly #220~~
* [x] Testing @RamirezAlex #212 
* [ ] ~~UI Components~~
* [ ] ~~[Miscellaneous](https://github.com/reactjs/es.reactjs.org/blob/master/content/community/tools-misc.md)~~

**Comment by RamirezAlex** [comment]
I would like to help with `Support`

**Comment by jpvg10** [comment]
I would like to help with `Courses`

**Comment by alejandronanez** [comment]
@RamirezAlex, @jvelezpo, @jpvg10 - You got them. Thanks! 🎉

**Comment by RamirezAlex** [comment]
Please review #207 🎉 `Support`

I would like to continue with `Podcasts`

**Comment by RamirezAlex** [comment]
Please review #209 `Podcasts`

I'd like to continue with `Meetups`

**Comment by RamirezAlex** [comment]
Please review #210 `Meetups`

I'd like to continue with `Testing`

**Comment by jpvg10** [comment]
#211 `Courses` ready for review

**Comment by RamirezAlex** [comment]
Please review #212 `Testing`

I'd like to continue with `Conferences`

**Comment by hextiandro** [comment]
I would like to help with Routing

**Comment by carburo** [comment]
Welcome @hextiandro! You got it.

**Comment by mact200590** [comment]
I would like to continue with Debugging

**Comment by carburo** [comment]
Ok, @mact200590, you got it. 🚀

**Comment by OmaritoAtPoly** [comment]
i'd like to colaborate with data fetching

**Comment by OmaritoAtPoly** [comment]
i wish to continue collaborating with UI Components

**Comment by carburo** [comment]
Hi, @OmaritoAtPoly. I see you are still working in Data Fetching (you created a Draft Pull Request). Once you are done with it you can take another one.

**Comment by OmaritoAtPoly** [comment]
I'm ready to obtain a new task.

**Comment by gonzarodriguezt** [comment]
I would like to contribute with `External Resources`.

**Comment by carburo** [comment]
Hi, @gonzarodriguezt! You got it.

**Comment by RamirezAlex** [comment]
Oh!!! I see I still have `Conferences`, I will send it soonish. Sorry about that.

**Comment by jmmendivil** [comment]
I would like to help with _Component Workbenches_

**Comment by carburo** [comment]
Welcome, @jmmendivil! You got it!

**Comment by jmmendivil** [comment]
`Component Workbenches` is ready for review on #311

**Comment by jpmti2016** [comment]
Hi @carburo, if you need more help with the Spanish translation please let me know. I see that conference, articles and videos would be not translated yet.

**Comment by carburo** [comment]
Hi @jpmti2016, thank you for reaching out! Yes, we do need help in translating more content. You can take any of the available pages, just let us know in a comment. There is also an open issue (#201) for all the blog posts.

**Comment by jpmti2016** [comment]
@carburo  I take articles and videos for now.

**Comment by carburo** [comment]
@jpmti2016 Great, thanks! They're yours

**Comment by jpmti2016** [comment]
@carburo Tengo dudas sobre cuál es el repo sobre el que debo hacer fork y cuál clonar, pues el punto 5 de los prerequisitos apunta a https://github.com/reactjs/reactjs.org. 

Ya tengo lista la traduccion de la página de artículos. La hize sobre el repo https://github.com/reactjs/reactjs.org, pero algo me dice que debería trabajar con https://github.com/reactjs/es.reactjs.org (el repo de la traducción en español) y hacer push and PR sobre este último.

**Comment by carburo** [comment]
@jpmti2016  Debes hacer el fork al repositorio de la documentación en español: es.reactjs.org. Creas una rama en ese fork y haces el PR desde allí.

**Comment by jpmti2016** [comment]
@carburo I made 2 PR para videos and articles respectively

**Comment by jean182** [comment]
I will be translating conferences, since I'm not seeing any translation for this and there's no recent comments for translating it.

**Comment by jean182** [comment]
Here's the PR for the conferences translation:
https://github.com/reactjs/es.reactjs.org/pull/361

**Comment by d4vsanchez** [comment]
Is the conferences translation made by #361 not deployed? Looking at https://es.reactjs.org/community/conferences.html I noticed that the website is still in English.

**Comment by carburo** [comment]
@d4vsanchez No, nunca llegó a mezclarse. Casi de forma inmediata tuvo conflictos con la rama principal. Esta página se actualiza con relativa  regularidad y el contenido traducible se limita sobre todo a las fechas. El problema no es traducirla, sino el costo de mantenerla actualizada. A menos que la solución incluya un proceso al menos semiautomático no creo que los beneficios superen los costos.
