### ISSUE TITLE
Wrong translation in https://es.reactjs.org/docs/introducing-jsx.html

### ISSUE THREAD

**Issue by seraco** [reactjs/es.reactjs.org#256]
Hey contributors,

After reading the translation of *Introducing JSX* I've noticed that the sentence **"Esto significa que puedes usar JSX dentro de declaraciones if y bucles for, asignarlo a variables, aceptarlo como argumentos, y retornarlo como funciones:"** doesn't reflect the exact meaning it has in English.

In my opinion, it should be: **"Esto significa que puedes usar JSX dentro de declaraciones if y bucles for, asignarlo a variables, aceptarlo como argumento, y retornarlo desde dentro de funciones:"**.

Let me know if you think the translation I propose can be improved.

**Comment by carburo** [comment]
Thank you! Yes, the translation doesn't reflect the original meaning. Could you submit a PR? If it is too much of a hassle, don't worry, let me know and I'll take care of it.

**Comment by seraco** [comment]
I'm gonna do a PR.
