### ISSUE TITLE
Hi @OliverPradaLara! Thank you for your contribution. As a general rule, we don't accept submissions for new content, only translations. Could you open this PR to the [upstream repo](https://github.com/reactjs/reactjs.org) so all translations benefit from this addition?

### ISSUE THREAD

**Issue by OliverPradaLara** [reactjs/es.reactjs.org#438]
Hi @OliverPradaLara! Thank you for your contribution. As a general rule, we don't accept submissions for new content, only translations. Could you open this PR to the [upstream repo](https://github.com/reactjs/reactjs.org) so all translations benefit from this addition?

_Originally posted by @carburo in https://github.com/reactjs/es.reactjs.org/issues/437#issuecomment-800225445_

**Comment by carburo** [comment]
Duplicate of #439
