### ISSUE TITLE
Santiago-Chile meetup addition rejected

### ISSUE THREAD

**Issue by OliverPradaLara** [reactjs/es.reactjs.org#439]
Greetings community, I have the following query: why can't I add my meetup group to the react community? On the react.org page it says that if I have a meetup group from my country I can add it but when I tried to do it it was rejected .

**Comment by carburo** [comment]
@OliverPradaLara No creo que haya ningún inconveniente en añadir este _meetup_. Sin embargo, este no es el repositorio original de la traducción de React, sino de su traducción oficial al español. Para añadir un contenido nuevo como este debe hacerse en el repositorio de la documentación en inglés https://github.com/reactjs/reactjs.org. Una vez que se apruebe allí, los cambios se mezclarán en todas las traducciones.
