### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by maogongzi** [reactjs/es.reactjs.org#440]
In markdown `es.reactjs.org/content/docs/reference-react-component.md`, **re utilización** would be better spelled as **reutilización**, original text:

> Recomendamos encarecidamente no crear tus propias clases de componentes base. En los componentes de React, la re utilización de código se consigue principalmente a través de la composición en lugar de la herencia.

**Comment by carburo** [comment]
Sí, completamente de acuerdo. ¿Desearía hacer el _pull request_ con el cambio?

**Comment by maogongzi** [comment]
> Sí, completamente de acuerdo. ¿Desearía hacer el _pull request_ con el cambio?

Por supuesto :)
