### ISSUE TITLE
Spelling error in documentation (language: Spanish)

### ISSUE THREAD

**Issue by GaboCuba** [reactjs/es.reactjs.org#447]
In the link:
https://es.reactjs.org/docs/hooks-reference.html#useref

The accent is missing in the word: "código".

Where it says: ... "Si quieres correr algún codigo cuando React agregue"...
I should say: ..."Si quieres correr algún código cuando React agregue"...

Greetings

PS: I already opened this issue on another page, but was recommended to open it here.
(https://github.com/reactjs/reactjs.org/issues/3604#issue-847242189)
Thanks to @eps1lon for that.

**Comment by carburo** [comment]
Hola, @GaboCuba: Perdona la confusión, este es el repositorio adecuado. Muchas gracias por detectar el error. Para referencias futuras, sí así lo deseara, los _pull requests_ que corrigen estos errores son bienvenidos, en cuyo caso no es necesario abrir un _issue_ previamente.
