### ISSUE TITLE
Tal vez un typo en "no solo ... si no"

### ISSUE THREAD

**Issue by maogongzi** [reactjs/es.reactjs.org#468]
Hola!  en el documento: https://github.com/reactjs/es.reactjs.org/blob/master/content/docs/testing-environments.md
tal vez es mejor escribir "**sino**" en vez de "**si no**" en el ultimo oración?

> y comprobar los efectos no solo del navegador si no potencialmente del backend también.

**Comment by carburo** [comment]
¡Hola! Muchas gracias por hacernos notar el error.
