### ISSUE TITLE
Typo in content/docs/lists-and-keys.md ?

### ISSUE THREAD

**Issue by maogongzi** [reactjs/es.reactjs.org#495]
Hi! While I'm reading [the part](https://es.reactjs.org/docs/lists-and-keys.html#embedding-map-in-jsx) in the screenshot below, I'm a little bit confused, instead of using "arriba", perhaps it should be "abajo" ?

![Screen Shot 2022-01-26 at 14 39 35](https://user-images.githubusercontent.com/1438835/151116589-2ea02290-5393-4a46-ad5d-0f94c06d42df.png)

**Comment by carburo** [comment]
Hola @maogongzi! Gracias por el reporte. En este caso la traducción es correcta, se refiere a los ejemplos anteriores en los que ya se declaraba `listItems` con la misma intención, solo que abajo se vuelve a mostrar para recordarlo. Cualquier reporte sobre la claridad del texto que no involucre la traducción es preferible hacerlo en el [repositorio original en inglés](https://github.com/reactjs/reactjs.org).
