### ISSUE TITLE
Typo in content/docs/thinking-in-react.md ?

### ISSUE THREAD

**Issue by maogongzi** [reactjs/es.reactjs.org#496]
Hi! I'm not sure if it's a typo [here](https://es.reactjs.org/docs/thinking-in-react.html#step-4-identify-where-your-state-should-live) in the screenshot:

![Screen Shot 2022-01-26 at 17 42 28](https://user-images.githubusercontent.com/1438835/151141296-4d604556-0765-4e1f-8b2f-1c2bb58facc1.png)

when I refer to the original text, it reads:

> If you can’t find a component where it makes sense to own the state, create a new component solely for holding the state and add it somewhere in the hierarchy above the common owner component.

And here we can see that the original verb is "find", not "create" :)

**Comment by habarahonaa** [comment]
yes:) seems like a typo here!

**Comment by carburo** [comment]
Perdona la respuesta tardía. Sí, definitivamente es una errata. Muchas gracias por el reporte, ya está solucionado.
